version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: banksoal-app
    container_name: banksoal-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_DATABASE=banksoal
      - DB_USERNAME=root
      - DB_PASSWORD=secret

  db:
    image: mysql:8.0
    container_name: banksoal-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: banksoal
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: